services:
  web:
    build:
        context: ..
        dockerfile: docker/Dockerfile
    container_name: my_web_app
    environment:
      UPLOAD_DIR: /usr/src/app/uploads
      DATABASE_HOST: my_db
      DATABASE_PORT: 5432
      DATABASE_USER: user
      DATABASE_PASSWORD: pass
      DATABASE_NAME: postgres
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/usr/src/app/uploads  # for persistent uploads
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: my_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: